import type { Article, Source, FundingRound, KPIData } from '../types';

export const MOCK_SOURCES: Source[] = [
  { id: 's1', name: 'OpenAI Blog', slug: 'openai', url: 'https://openai.com/blog', rss_url: null, company: 'OpenAI', category: 'company', color: '#10B981', icon_letter: 'O', is_active: true, article_count: 48, last_synced_at: new Date(Date.now() - 18 * 60000).toISOString(), created_at: '' },
  { id: 's2', name: 'Anthropic News', slug: 'anthropic', url: 'https://anthropic.com', rss_url: null, company: 'Anthropic', category: 'company', color: '#F97316', icon_letter: 'A', is_active: true, article_count: 36, last_synced_at: new Date(Date.now() - 22 * 60000).toISOString(), created_at: '' },
  { id: 's3', name: 'Google DeepMind', slug: 'deepmind', url: 'https://deepmind.google', rss_url: null, company: 'Google', category: 'company', color: '#4285F4', icon_letter: 'D', is_active: true, article_count: 29, last_synced_at: new Date(Date.now() - 25 * 60000).toISOString(), created_at: '' },
  { id: 's4', name: 'Google AI Blog', slug: 'google-ai', url: 'https://ai.googleblog.com', rss_url: null, company: 'Google', category: 'company', color: '#34A853', icon_letter: 'G', is_active: true, article_count: 41, last_synced_at: new Date(Date.now() - 28 * 60000).toISOString(), created_at: '' },
  { id: 's5', name: 'Microsoft AI', slug: 'microsoft-ai', url: 'https://blogs.microsoft.com/ai', rss_url: null, company: 'Microsoft', category: 'company', color: '#00A4EF', icon_letter: 'M', is_active: true, article_count: 33, last_synced_at: new Date(Date.now() - 31 * 60000).toISOString(), created_at: '' },
  { id: 's6', name: 'Meta AI', slug: 'meta-ai', url: 'https://ai.meta.com', rss_url: null, company: 'Meta', category: 'company', color: '#1877F2', icon_letter: 'F', is_active: true, article_count: 27, last_synced_at: new Date(Date.now() - 35 * 60000).toISOString(), created_at: '' },
  { id: 's7', name: 'NVIDIA Blog', slug: 'nvidia', url: 'https://blogs.nvidia.com', rss_url: null, company: 'NVIDIA', category: 'company', color: '#76B900', icon_letter: 'N', is_active: true, article_count: 22, last_synced_at: new Date(Date.now() - 40 * 60000).toISOString(), created_at: '' },
  { id: 's8', name: 'Hugging Face', slug: 'huggingface', url: 'https://huggingface.co/blog', rss_url: null, company: 'Hugging Face', category: 'company', color: '#F59E0B', icon_letter: 'H', is_active: true, article_count: 55, last_synced_at: new Date(Date.now() - 45 * 60000).toISOString(), created_at: '' },
  { id: 's9', name: 'TechCrunch AI', slug: 'techcrunch-ai', url: 'https://techcrunch.com', rss_url: null, company: null, category: 'media', color: '#00CC44', icon_letter: 'T', is_active: true, article_count: 120, last_synced_at: new Date(Date.now() - 12 * 60000).toISOString(), created_at: '' },
  { id: 's10', name: 'VentureBeat AI', slug: 'venturebeat-ai', url: 'https://venturebeat.com', rss_url: null, company: null, category: 'media', color: '#E11D48', icon_letter: 'V', is_active: true, article_count: 98, last_synced_at: new Date(Date.now() - 15 * 60000).toISOString(), created_at: '' },
  { id: 's11', name: 'The Verge AI', slug: 'verge-ai', url: 'https://theverge.com', rss_url: null, company: null, category: 'media', color: '#FA4616', icon_letter: 'V', is_active: true, article_count: 76, last_synced_at: new Date(Date.now() - 20 * 60000).toISOString(), created_at: '' },
  { id: 's12', name: 'MIT Tech Review', slug: 'mit-tech-review', url: 'https://technologyreview.com', rss_url: null, company: null, category: 'media', color: '#A00000', icon_letter: 'M', is_active: true, article_count: 44, last_synced_at: new Date(Date.now() - 60 * 60000).toISOString(), created_at: '' },
  { id: 's13', name: 'AI News', slug: 'ai-news', url: 'https://artificialintelligence-news.com', rss_url: null, company: null, category: 'media', color: '#6366F1', icon_letter: 'A', is_active: true, article_count: 67, last_synced_at: new Date(Date.now() - 8 * 60000).toISOString(), created_at: '' },
];

const now = Date.now();
export const MOCK_ARTICLES: Article[] = [
  { id: 'a1', source_id: 's1', source_name: 'OpenAI Blog', source_color: '#10B981', title: 'GPT-5 Achieves State-of-the-Art on Complex Reasoning and Code Generation', summary: 'OpenAI releases GPT-5 with unprecedented performance on mathematical olympiad problems, competitive programming benchmarks, and multi-step reasoning tasks.', url: '#', image_url: null, author: 'OpenAI Team', published_at: new Date(now - 2 * 3600000).toISOString(), category: 'models', tags: ['GPT-5', 'reasoning', 'benchmarks'], company: 'OpenAI', article_type: 'announcement', read_time: 6, is_featured: true, view_count: 8420, created_at: '' },
  { id: 'a2', source_id: 's2', source_name: 'Anthropic News', source_color: '#F97316', title: "Claude's Extended Context Now Handles 2 Million Tokens — Here's What That Unlocks", summary: 'Anthropic expands Claude context windows to 2M tokens, enabling analysis of entire codebases, lengthy legal documents, and multi-day conversations.', url: '#', image_url: null, author: 'Anthropic Research', published_at: new Date(now - 5 * 3600000).toISOString(), category: 'models', tags: ['Claude', 'context-window', 'long-context'], company: 'Anthropic', article_type: 'announcement', read_time: 5, is_featured: false, view_count: 5210, created_at: '' },
  { id: 'a3', source_id: 's3', source_name: 'Google DeepMind', source_color: '#4285F4', title: 'AlphaFold 3 Expands to Predict Drug-Protein Interactions at Atomic Precision', summary: 'DeepMind extends AlphaFold 3 to model small molecule binding, accelerating drug discovery for diseases like Alzheimers and cancer.', url: '#', image_url: null, author: 'DeepMind Science', published_at: new Date(now - 8 * 3600000).toISOString(), category: 'research', tags: ['AlphaFold', 'drug-discovery', 'biology'], company: 'Google', article_type: 'research', read_time: 8, is_featured: false, view_count: 4180, created_at: '' },
  { id: 'a4', source_id: 's4', source_name: 'Google AI Blog', source_color: '#34A853', title: 'Gemini 2.0 Flash: 10x Speed Improvement with Multimodal Capabilities', summary: 'Google releases Gemini 2.0 Flash, delivering 10x inference speed over Gemini 1.5 Flash while matching accuracy on most benchmarks.', url: '#', image_url: null, author: 'Google AI Team', published_at: new Date(now - 12 * 3600000).toISOString(), category: 'models', tags: ['Gemini', 'multimodal', 'performance'], company: 'Google', article_type: 'announcement', read_time: 4, is_featured: false, view_count: 3560, created_at: '' },
  { id: 'a5', source_id: 's5', source_name: 'Microsoft AI', source_color: '#00A4EF', title: 'Copilot Integrated Into Every Microsoft 365 App — What You Need to Know', summary: 'Microsoft announces deep Copilot integration across Word, Excel, PowerPoint, Teams, and Outlook with new agentic capabilities.', url: '#', image_url: null, author: 'Microsoft Blog', published_at: new Date(now - 18 * 3600000).toISOString(), category: 'products', tags: ['Copilot', 'Microsoft-365', 'enterprise'], company: 'Microsoft', article_type: 'news', read_time: 5, is_featured: false, view_count: 6890, created_at: '' },
  { id: 'a6', source_id: 's6', source_name: 'Meta AI', source_color: '#1877F2', title: 'Llama 4 Open Source Release: Matches GPT-4o on Key Benchmarks', summary: 'Meta releases Llama 4 family under Apache 2.0 license. The 70B model achieves competitive performance on MMLU, HumanEval, and reasoning tasks.', url: '#', image_url: null, author: 'Meta AI Research', published_at: new Date(now - 24 * 3600000).toISOString(), category: 'models', tags: ['Llama-4', 'open-source', 'Meta'], company: 'Meta', article_type: 'announcement', read_time: 6, is_featured: false, view_count: 9120, created_at: '' },
  { id: 'a7', source_id: 's7', source_name: 'NVIDIA Blog', source_color: '#76B900', title: 'NVIDIA NIM Microservices Now Available for Enterprise AI Deployment', summary: 'NVIDIA launches NIM microservices for one-click deployment of AI models in enterprise environments, supporting Llama, Mistral, and custom fine-tuned models.', url: '#', image_url: null, author: 'NVIDIA Enterprise', published_at: new Date(now - 30 * 3600000).toISOString(), category: 'products', tags: ['NIM', 'enterprise', 'deployment'], company: 'NVIDIA', article_type: 'news', read_time: 4, is_featured: false, view_count: 2780, created_at: '' },
  { id: 'a8', source_id: 's8', source_name: 'Hugging Face', source_color: '#F59E0B', title: 'Hugging Face Hub Surpasses 1 Million Open-Source AI Models', summary: 'The open-source AI platform reaches a milestone with over 1 million models, 250,000 datasets, and 500,000 community spaces.', url: '#', image_url: null, author: 'HF Team', published_at: new Date(now - 36 * 3600000).toISOString(), category: 'open-source', tags: ['open-source', 'community', 'milestone'], company: 'Hugging Face', article_type: 'news', read_time: 3, is_featured: false, view_count: 4560, created_at: '' },
  { id: 'a9', source_id: 's9', source_name: 'TechCrunch AI', source_color: '#00CC44', title: "OpenAI's Valuation Hits $157B After Closing $6.6B Funding Round", summary: 'OpenAI closes its largest funding round to date, with participation from Microsoft, Tiger Global, and SoftBank, at a $157B post-money valuation.', url: '#', image_url: null, author: 'Kyle Wiggers', published_at: new Date(now - 42 * 3600000).toISOString(), category: 'funding', tags: ['funding', 'OpenAI', 'valuation'], company: 'OpenAI', article_type: 'funding', read_time: 4, is_featured: false, view_count: 12300, created_at: '' },
  { id: 'a10', source_id: 's10', source_name: 'VentureBeat AI', source_color: '#E11D48', title: 'Amazon Invests Additional $4 Billion in Anthropic to Deepen AI Partnership', summary: 'Amazon completes its commitment to invest up to $4B in Anthropic, making it the largest AWS strategic investment. Anthropic will use AWS as primary cloud provider.', url: '#', image_url: null, author: 'Michael Nuñez', published_at: new Date(now - 48 * 3600000).toISOString(), category: 'funding', tags: ['Anthropic', 'Amazon', 'partnership'], company: 'Anthropic', article_type: 'funding', read_time: 5, is_featured: false, view_count: 7840, created_at: '' },
  { id: 'a11', source_id: 's11', source_name: 'The Verge AI', source_color: '#FA4616', title: 'EU AI Act Takes Effect: What Every AI Company Must Do Now', summary: 'The European Union\'s landmark AI regulation has entered into force. Here\'s a breakdown of compliance requirements for foundation model providers and deployers.', url: '#', image_url: null, author: 'James Vincent', published_at: new Date(now - 54 * 3600000).toISOString(), category: 'regulation', tags: ['EU-AI-Act', 'regulation', 'compliance'], company: null, article_type: 'news', read_time: 7, is_featured: false, view_count: 9870, created_at: '' },
  { id: 'a12', source_id: 's12', source_name: 'MIT Tech Review', source_color: '#A00000', title: "The Problem With AI's Energy Hunger — And What Can Be Done About It", summary: 'Data centers training frontier AI models consume enormous amounts of electricity. Researchers examine efficiency improvements and renewable energy commitments.', url: '#', image_url: null, author: 'Casey Crownhart', published_at: new Date(now - 60 * 3600000).toISOString(), category: 'research', tags: ['energy', 'climate', 'infrastructure'], company: null, article_type: 'research', read_time: 9, is_featured: false, view_count: 5430, created_at: '' },
  { id: 'a13', source_id: 's13', source_name: 'AI News', source_color: '#6366F1', title: 'Scale AI Raises $1B Series F for AI Data Infrastructure Platform', summary: 'Scale AI secures $1 billion in Series F funding to expand its data labeling and evaluation infrastructure used by leading AI labs.', url: '#', image_url: null, author: 'AI News Staff', published_at: new Date(now - 72 * 3600000).toISOString(), category: 'funding', tags: ['Scale-AI', 'funding', 'data'], company: null, article_type: 'funding', read_time: 3, is_featured: false, view_count: 3210, created_at: '' },
  { id: 'a14', source_id: 's1', source_name: 'OpenAI Blog', source_color: '#10B981', title: 'Introducing OpenAI DevDay 2024: New API Features for Developers', summary: 'OpenAI unveils new API capabilities including prompt caching, fine-tuning improvements, and a new Realtime API for voice applications.', url: '#', image_url: null, author: 'OpenAI', published_at: new Date(now - 84 * 3600000).toISOString(), category: 'products', tags: ['API', 'developers', 'DevDay'], company: 'OpenAI', article_type: 'announcement', read_time: 5, is_featured: false, view_count: 7650, created_at: '' },
  { id: 'a15', source_id: 's2', source_name: 'Anthropic News', source_color: '#F97316', title: 'Claude for Enterprise: New Team Features and Compliance Controls', summary: 'Anthropic launches Claude Teams and Enterprise tiers with SSO, audit logs, custom system prompts, and SOC 2 Type II compliance.', url: '#', image_url: null, author: 'Anthropic', published_at: new Date(now - 96 * 3600000).toISOString(), category: 'products', tags: ['enterprise', 'Teams', 'compliance'], company: 'Anthropic', article_type: 'announcement', read_time: 4, is_featured: false, view_count: 4890, created_at: '' },
  { id: 'a16', source_id: 's8', source_name: 'Hugging Face', source_color: '#F59E0B', title: 'Open LLM Leaderboard v2: New Benchmarks for the Post-GPT-4 Era', summary: 'Hugging Face revamps the Open LLM Leaderboard with harder benchmarks designed to evaluate reasoning, coding, and instruction following at the frontier.', url: '#', image_url: null, author: 'HF Research', published_at: new Date(now - 108 * 3600000).toISOString(), category: 'research', tags: ['benchmarks', 'leaderboard', 'evaluation'], company: 'Hugging Face', article_type: 'research', read_time: 6, is_featured: false, view_count: 6230, created_at: '' },
  { id: 'a17', source_id: 's3', source_name: 'Google DeepMind', source_color: '#4285F4', title: 'Gemini Nano Runs Fully On-Device: Privacy-First AI for Android', summary: 'Google ships Gemini Nano to Pixel 8 Pro and Galaxy S24 devices, enabling summarization, smart replies, and recording transcription without cloud connectivity.', url: '#', image_url: null, author: 'DeepMind', published_at: new Date(now - 120 * 3600000).toISOString(), category: 'products', tags: ['Gemini-Nano', 'on-device', 'mobile'], company: 'Google', article_type: 'news', read_time: 4, is_featured: false, view_count: 5670, created_at: '' },
  { id: 'a18', source_id: 's5', source_name: 'Microsoft AI', source_color: '#00A4EF', title: 'Azure AI Studio Launches Prompt Flow and Model Catalog Updates', summary: 'Microsoft updates Azure AI Studio with enhanced prompt flow orchestration, 1,600+ model catalog, and new safety evaluation tools.', url: '#', image_url: null, author: 'Azure Team', published_at: new Date(now - 132 * 3600000).toISOString(), category: 'products', tags: ['Azure', 'AI-Studio', 'cloud'], company: 'Microsoft', article_type: 'news', read_time: 5, is_featured: false, view_count: 3120, created_at: '' },
  { id: 'a19', source_id: 's6', source_name: 'Meta AI', source_color: '#1877F2', title: 'Meta AI Assistant Launches Across WhatsApp, Instagram, and Messenger', summary: 'Meta rolls out its AI assistant to 3 billion users across its messaging platforms, with real-time web search powered by Bing and image generation.', url: '#', image_url: null, author: 'Meta AI', published_at: new Date(now - 144 * 3600000).toISOString(), category: 'products', tags: ['Meta-AI', 'WhatsApp', 'assistant'], company: 'Meta', article_type: 'news', read_time: 3, is_featured: false, view_count: 11400, created_at: '' },
  { id: 'a20', source_id: 's7', source_name: 'NVIDIA Blog', source_color: '#76B900', title: 'H200 SXM Availability: How to Access NVIDIA\'s Latest AI Accelerator', summary: 'NVIDIA announces H200 SXM availability through all major cloud providers. The new GPU offers 2x memory bandwidth improvement over H100.', url: '#', image_url: null, author: 'NVIDIA', published_at: new Date(now - 156 * 3600000).toISOString(), category: 'hardware', tags: ['H200', 'GPU', 'cloud'], company: 'NVIDIA', article_type: 'news', read_time: 4, is_featured: false, view_count: 4320, created_at: '' },
];

export const MOCK_FUNDING: FundingRound[] = [
  { id: 'f1', company_name: 'OpenAI', amount: '$6.6B', amount_usd: 6600000000, investors: ['Microsoft', 'Tiger Global', 'SoftBank'], round_type: 'Series B', sector: 'Foundation Models', announced_at: new Date(now - 5 * 86400000).toISOString(), article_url: '#', created_at: '' },
  { id: 'f2', company_name: 'Anthropic', amount: '$4.0B', amount_usd: 4000000000, investors: ['Amazon', 'Spark Capital', 'Google'], round_type: 'Strategic', sector: 'Foundation Models', announced_at: new Date(now - 10 * 86400000).toISOString(), article_url: '#', created_at: '' },
  { id: 'f3', company_name: 'xAI (Grok)', amount: '$6.0B', amount_usd: 6000000000, investors: ['Andreessen Horowitz', 'Sequoia Capital', 'Kingdom Holdings'], round_type: 'Series B', sector: 'Foundation Models', announced_at: new Date(now - 15 * 86400000).toISOString(), article_url: '#', created_at: '' },
  { id: 'f4', company_name: 'Mistral AI', amount: '$1.08B', amount_usd: 1080000000, investors: ['Andreessen Horowitz', 'BNP Paribas', 'Salesforce'], round_type: 'Series B', sector: 'Foundation Models', announced_at: new Date(now - 20 * 86400000).toISOString(), article_url: '#', created_at: '' },
  { id: 'f5', company_name: 'Scale AI', amount: '$1.0B', amount_usd: 1000000000, investors: ['Amazon', 'Meta', 'Nvidia'], round_type: 'Series F', sector: 'AI Infrastructure', announced_at: new Date(now - 25 * 86400000).toISOString(), article_url: '#', created_at: '' },
  { id: 'f6', company_name: 'Cohere', amount: '$500M', amount_usd: 500000000, investors: ['Nvidia', 'Salesforce', 'Oracle'], round_type: 'Series D', sector: 'Enterprise AI', announced_at: new Date(now - 30 * 86400000).toISOString(), article_url: '#', created_at: '' },
];

export const MOCK_KPI: KPIData = {
  total_articles: 687,
  articles_today: 24,
  articles_this_week: 147,
  active_sources: 13,
  total_funding_usd: 19180000000,
  latest_sync: new Date(now - 8 * 60000).toISOString(),
};
